apiVersion: v1
kind: Service
metadata:
  name: consolportals-it-fastweb-vcp-ccportal-service
  namespace: fastweb-vcp-services
  labels:
    app.kubernetes.io/name: vcp-ccportal
    app.kubernetes.io/part-of: consolportals
spec:
  type: ClusterIP
  selector:
    component: vcp-ccportal
  ports:
    - name: http
      port: 8081
      targetPort: 8081
