apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: consolportals-it-fastweb-vcp-httpd-pdb
  namespace: fastweb-vcp-services
spec:
  minAvailable: 1
  selector:
    matchLabels:
      component: vcp-httpd
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: consolportals-it-fastweb-vcp-a3gw-pdb
  namespace: fastweb-vcp-services
spec:
  minAvailable: 1
  selector:
    matchLabels:
      component: vcp-a3gw
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: consolportals-it-fastweb-vcp-adminportal-pdb
  namespace: fastweb-vcp-services
spec:
  minAvailable: 1
  selector:
    matchLabels:
      component: vcp-adminportal
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: consolportals-it-fastweb-vcp-ccportal-pdb
  namespace: fastweb-vcp-services
spec:
  minAvailable: 1
  selector:
    matchLabels:
      component: vcp-ccportal
---
