apiVersion: v1
kind: Pod
metadata:
  name: consolportals-it-fastweb-vcp-adminportal
  labels:
    component: vcp-adminportal
spec:
  containers:
    - name: vcp-adminportal
      image: nexus.telenity.com/com/telenity/consolportals-it-fastweb-vcp-adminportal:1.0.0.0
      ports:
        - containerPort: 8080
